# Generated by Django 5.0.6 on 2024-05-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TouristSpots", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ToutistSpots",
            new_name="TouristSpots",
        ),
    ]
